<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[TEST SCRIPT IS FAILED]]>
    </line>
    <line>
      <![CDATA[TEST SCRIPT IS PASSED]]>
    </line>
  </reporter-output>
  <suite started-at="2025-05-21T08:44:33 IST" name="Default suite" finished-at="2025-05-21T08:44:40 IST" duration-ms="6594">
    <groups>
    </groups>
    <test started-at="2025-05-21T08:44:33 IST" name="Default test" finished-at="2025-05-21T08:44:40 IST" duration-ms="6594">
      <class name="sauce.LoginTests">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:sauce.LoginTests@4b2bac3f]" started-at="2025-05-21T08:44:33 IST" name="openBrowser" finished-at="2025-05-21T08:44:36 IST" duration-ms="2577" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="InvalidUN()[pri:0, instance:sauce.LoginTests@4b2bac3f]" started-at="2025-05-21T08:44:36 IST" name="InvalidUN" finished-at="2025-05-21T08:44:36 IST" duration-ms="561" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Proper Error message is not displayed expected [Epic sadface: Username and password do not match any use in this service] but found [Epic sadface: Username and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Proper Error message is not displayed expected [Epic sadface: Username and password do not match any use in this service] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at sauce.LoginTests.InvalidUN(LoginTests.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TEST SCRIPT IS FAILED]]>
            </line>
          </reporter-output>
        </test-method> <!-- InvalidUN -->
        <test-method is-config="true" signature="logout()[pri:0, instance:sauce.LoginTests@4b2bac3f]" started-at="2025-05-21T08:44:36 IST" name="logout" finished-at="2025-05-21T08:44:37 IST" duration-ms="242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:sauce.LoginTests@4b2bac3f]" started-at="2025-05-21T08:44:37 IST" name="openBrowser" finished-at="2025-05-21T08:44:39 IST" duration-ms="1961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="validCred()[pri:0, instance:sauce.LoginTests@4b2bac3f]" started-at="2025-05-21T08:44:39 IST" name="validCred" finished-at="2025-05-21T08:44:39 IST" duration-ms="559" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TEST SCRIPT IS PASSED]]>
            </line>
          </reporter-output>
        </test-method> <!-- validCred -->
        <test-method is-config="true" signature="logout()[pri:0, instance:sauce.LoginTests@4b2bac3f]" started-at="2025-05-21T08:44:39 IST" name="logout" finished-at="2025-05-21T08:44:40 IST" duration-ms="483" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- sauce.LoginTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
